firstInput = int(input("Enter First Number:"))
a = firstInput
secondInput = int(input("Enter Second Number:"))
b = secondInput
a += b
print(firstInput,"+", secondInput, "=", a)
a -= b
print(firstInput,"-", secondInput, "=", a)
a *= b
print(firstInput,"*", secondInput, "=", a)
a /= b
print(firstInput,"/", secondInput, "=", a)